### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by BobbeYo1983** [Vivecstel/Jetpack-Compose-Playground#1]
Good day! The build errors are as follows:

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'
Caused by: org.gradle.api.GradleException: The com.google.protobuf plugin could not be applied during project evaluation. The Java plugin or one of the Android plugins must be applied to the project first
at com.google.protobuf.gradle.ProtobufPlugin$_apply_closure3.doCall(ProtobufPlugin.groovy:111)

What versions of IDE, Android Gradle and Gradle did you build?

**Comment by Vivecstel** [comment]
Hello @BobbeYo1983 ,

I currently use latest Android Studio Beta (beta 2), Android gradle plugin (7.0.0-beta02) and gradle 7.0.2.
Note that you need Java 11 to run it.
I added today a small instructions section on how to run it. I will update it the next days with more specific information.
Try it with this configuration and tell me if ok.

**Comment by BobbeYo1983** [comment]
Yes, the project was assembled in the studio (beta2), did not compile and did not load on the device, it is enough for me to look at the code for now. Thank you, kind person).

You, by any chance do not work in Google?

**Comment by Vivecstel** [comment]
haha no I don't work for google.
Can you try comment out the protobuf / datastore gradle / kotlin code ?
This is not needed to run the examples. I can prepare you a branch with that.
Or did you get another error ?
Did you try adding new app id and google services json with Java 11 ? I tried it yesterday on a new clone repo and added some fixes in the build gradle file.

**Comment by BobbeYo1983** [comment]
I have the codes and have the app installed, that's enough for me. I propose to close the problem.
But there will probably be questions about the code and I would be grateful if you could help)

**Comment by Vivecstel** [comment]
Sure. Ping me when you have a question.
Thanks

**Comment by BobbeYo1983** [comment]
On another machine, the error is as follows:
_The Hilt Android Gradle plugin is applied but no com.google.dagger:hilt-android dependency was found._

**Comment by BobbeYo1983** [comment]
Updated, made a clone, gathered

**Comment by Vivecstel** [comment]
So @BobbeYo1983 at the second machine did you successfully run it ? It seems weird getting these errors. Maybe beta studio issues ?

**Comment by BobbeYo1983** [comment]
Yes, it worked, just the codes were old, updated.
