### ISSUE TITLE
Search doesn't work as expected with uppercase characters

### ISSUE THREAD

**Issue by adrinieto** [Vivecstel/Jetpack-Compose-Playground#2]
It looks like it only works in lowercase.

Better to see it with two examples:

<img src="https://user-images.githubusercontent.com/908250/124777593-9e335f80-df40-11eb-8dff-c9568dfe5208.png" width=250px /> <img src="https://user-images.githubusercontent.com/908250/124777608-a095b980-df40-11eb-8ad3-7fc3c2eb94b0.png" width=250px />

Thanks for the app, it's really useful to see what Compose offers :smile:

**Comment by Vivecstel** [comment]
Thanks @adrinieto for the finding. I will provide fix today.

**Comment by Vivecstel** [comment]
Fixed in version 2.0.1
