### ISSUE TITLE
[Improvement Suggestion] Search Bar

### ISSUE THREAD

**Issue by jsericksk** [Vivecstel/Jetpack-Compose-Playground#4]
Provide a left and right icon for a better search UI, something like the image below:

![Screenshot_20210819-152638~01 1](https://user-images.githubusercontent.com/36176569/130124348-089779e6-0961-439a-b05e-3334c6b3a553.png)

Like (untested code :), in SearchTextField():

```
    leadingIcon = {
        Icon(imageVector = Icons.Default.Search, contentDescription = "")
    },
    trailingIcon = {
        IconButton(
            onClick = {
                searchText = ""
            }
        ) {
            Icon(imageVector = Icons.Default.Close, contentDescription = "")
        }
    }
```

**Comment by Vivecstel** [comment]
Thanks for the suggestion @jsericksk :) I will try it for next release

**Comment by jsericksk** [comment]
Ok. Great job, your app is helping a lot!
